language: ruby
cache: bundler
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env: DISPLAY=':99.0'
before_script:
  - gem update --system
  - RAILS_ENV=test bin/rails db:migrate
script:
  - bin/rails test:system
install: bundle install --without development
