language: ruby
cache: bundler
dist: trusty
env:
  DISPLAY: :99.0
  RAILS_ENV: test
  CHROME_DRIVER_VERSION: '2.30'
addons:
  chrome: beta
before_script:
  - bin/travis_system_setup.sh
script:
  - bin/rails test:system
install: bundle install --without development
